import type { Workspace } from '@/types/model'

/** Big Bank plc — classic Structurizr example workspace */
export function createBigBankSample(): Workspace {
  return {
    name: 'Big Bank plc',
    description: 'A model of the Big Bank plc software system landscape.',
    model: {
      people: [
        {
          id: 'customer',
          type: 'person',
          name: 'Personal Banking Customer',
          description: 'A customer of the bank, with personal bank accounts.',
          tags: ['Person', 'Customer'],
          properties: {},
          location: 'External',
        },
        {
          id: 'supportStaff',
          type: 'person',
          name: 'Customer Service Staff',
          description: 'Customer service staff within the bank.',
          tags: ['Person', 'Bank Staff'],
          properties: {},
          location: 'Internal',
        },
        {
          id: 'backoffice',
          type: 'person',
          name: 'Back Office Staff',
          description: 'Administration and support staff within the bank.',
          tags: ['Person', 'Bank Staff'],
          properties: {},
          location: 'Internal',
        },
      ],
      softwareSystems: [
        {
          id: 'internetBanking',
          type: 'softwareSystem',
          name: 'Internet Banking System',
          description: 'Allows customers to view information about their bank accounts, and make payments.',
          tags: ['Software System'],
          properties: {},
          location: 'Internal',
          containers: [
            {
              id: 'singlePageApp',
              type: 'container',
              name: 'Single-Page Application',
              description: 'Provides all of the Internet banking functionality to customers via their web browser.',
              technology: 'JavaScript, Angular',
              tags: ['Container'],
              properties: {},
              components: [],
            },
            {
              id: 'mobileApp',
              type: 'container',
              name: 'Mobile App',
              description: 'Provides a limited subset of the Internet banking functionality to customers via their mobile device.',
              technology: 'Xamarin',
              tags: ['Container'],
              properties: {},
              components: [],
            },
            {
              id: 'webApp',
              type: 'container',
              name: 'Web Application',
              description: 'Delivers the single page application.',
              technology: 'Java, Spring MVC',
              tags: ['Container'],
              properties: {},
              components: [],
            },
            {
              id: 'apiApp',
              type: 'container',
              name: 'API Application',
              description: 'Provides Internet banking functionality via a JSON/HTTPS API.',
              technology: 'Java, Spring MVC',
              tags: ['Container'],
              properties: {},
              components: [
                {
                  id: 'signinController',
                  type: 'component',
                  name: 'Sign In Controller',
                  description: 'Allows users to sign in to the Internet Banking System.',
                  technology: 'Spring MVC Controller',
                  tags: ['Component'],
                  properties: {},
                },
                {
                  id: 'resetPassController',
                  type: 'component',
                  name: 'Reset Password Controller',
                  description: 'Allows users to reset their passwords.',
                  technology: 'Spring MVC Controller',
                  tags: ['Component'],
                  properties: {},
                },
                {
                  id: 'accountsSummary',
                  type: 'component',
                  name: 'Accounts Summary Controller',
                  description: 'Provides customers with a summary of their bank accounts.',
                  technology: 'Spring MVC Controller',
                  tags: ['Component'],
                  properties: {},
                },
                {
                  id: 'securityComponent',
                  type: 'component',
                  name: 'Security Component',
                  description: 'Provides functionality related to signing in, changing passwords, etc.',
                  technology: 'Spring Bean',
                  tags: ['Component'],
                  properties: {},
                },
                {
                  id: 'emailComponent',
                  type: 'component',
                  name: 'E-mail Component',
                  description: 'Sends e-mails to users.',
                  technology: 'Spring Bean',
                  tags: ['Component'],
                  properties: {},
                },
                {
                  id: 'mainframeFacade',
                  type: 'component',
                  name: 'Mainframe Banking System Facade',
                  description: 'A facade onto the mainframe banking system.',
                  technology: 'Spring Bean',
                  tags: ['Component'],
                  properties: {},
                },
              ],
            },
            {
              id: 'database',
              type: 'container',
              name: 'Database',
              description: 'Stores user registration information, hashed authentication credentials, access logs, etc.',
              technology: 'Oracle 12c',
              tags: ['Container', 'Database'],
              properties: {},
              components: [],
            },
          ],
        },
        {
          id: 'mainframe',
          type: 'softwareSystem',
          name: 'Mainframe Banking System',
          description: 'Stores all of the core banking information about customers, accounts, transactions, etc.',
          tags: ['Software System', 'Existing System'],
          properties: {},
          location: 'Internal',
          containers: [],
        },
        {
          id: 'email',
          type: 'softwareSystem',
          name: 'E-mail System',
          description: 'The internal Microsoft Exchange e-mail system.',
          tags: ['Software System', 'Existing System'],
          properties: {},
          location: 'Internal',
          containers: [],
        },
        {
          id: 'atm',
          type: 'softwareSystem',
          name: 'ATM',
          description: 'Allows customers to withdraw cash.',
          tags: ['Software System', 'Existing System'],
          properties: {},
          location: 'Internal',
          containers: [],
        },
      ],
      relationships: [
        // System landscape level
        { id: 'r1', sourceId: 'customer', destinationId: 'internetBanking', description: 'Views account balances and makes payments', tags: ['Relationship'], properties: {} },
        { id: 'r2', sourceId: 'internetBanking', destinationId: 'mainframe', description: 'Gets account information from', tags: ['Relationship'], properties: {} },
        { id: 'r3', sourceId: 'internetBanking', destinationId: 'email', description: 'Sends e-mail using', tags: ['Relationship'], properties: {} },
        { id: 'r4', sourceId: 'email', destinationId: 'customer', description: 'Sends e-mails to', tags: ['Relationship'], properties: {} },
        { id: 'r5', sourceId: 'customer', destinationId: 'supportStaff', description: 'Asks questions to', technology: 'Telephone', tags: ['Relationship'], properties: {} },
        { id: 'r6', sourceId: 'supportStaff', destinationId: 'mainframe', description: 'Uses', tags: ['Relationship'], properties: {} },
        { id: 'r7', sourceId: 'customer', destinationId: 'atm', description: 'Withdraws cash', tags: ['Relationship'], properties: {} },
        { id: 'r8', sourceId: 'atm', destinationId: 'mainframe', description: 'Uses', tags: ['Relationship'], properties: {} },
        { id: 'r9', sourceId: 'backoffice', destinationId: 'mainframe', description: 'Uses', tags: ['Relationship'], properties: {} },
        // Container level
        { id: 'r10', sourceId: 'customer', destinationId: 'webApp', description: 'Visits', technology: 'HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r11', sourceId: 'customer', destinationId: 'singlePageApp', description: 'Views and interacts', tags: ['Relationship'], properties: {} },
        { id: 'r12', sourceId: 'customer', destinationId: 'mobileApp', description: 'Views and interacts', tags: ['Relationship'], properties: {} },
        { id: 'r13', sourceId: 'webApp', destinationId: 'singlePageApp', description: 'Delivers', tags: ['Relationship'], properties: {} },
        { id: 'r14', sourceId: 'singlePageApp', destinationId: 'apiApp', description: 'Makes API calls', technology: 'JSON/HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r15', sourceId: 'mobileApp', destinationId: 'apiApp', description: 'Makes API calls', technology: 'JSON/HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r16', sourceId: 'apiApp', destinationId: 'database', description: 'Reads from and writes to', technology: 'JDBC', tags: ['Relationship'], properties: {} },
        { id: 'r17', sourceId: 'apiApp', destinationId: 'mainframe', description: 'Makes API calls', technology: 'XML/HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r18', sourceId: 'apiApp', destinationId: 'email', description: 'Sends e-mail using', technology: 'SMTP', tags: ['Relationship'], properties: {} },
        // Component level
        { id: 'r19', sourceId: 'singlePageApp', destinationId: 'signinController', description: 'Makes API calls', technology: 'JSON/HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r20', sourceId: 'singlePageApp', destinationId: 'resetPassController', description: 'Makes API calls', technology: 'JSON/HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r21', sourceId: 'singlePageApp', destinationId: 'accountsSummary', description: 'Makes API calls', technology: 'JSON/HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r22', sourceId: 'signinController', destinationId: 'securityComponent', description: 'Uses', tags: ['Relationship'], properties: {} },
        { id: 'r23', sourceId: 'resetPassController', destinationId: 'securityComponent', description: 'Uses', tags: ['Relationship'], properties: {} },
        { id: 'r24', sourceId: 'resetPassController', destinationId: 'emailComponent', description: 'Uses', tags: ['Relationship'], properties: {} },
        { id: 'r25', sourceId: 'accountsSummary', destinationId: 'mainframeFacade', description: 'Uses', tags: ['Relationship'], properties: {} },
        { id: 'r26', sourceId: 'securityComponent', destinationId: 'database', description: 'Reads from and writes to', technology: 'JDBC', tags: ['Relationship'], properties: {} },
        { id: 'r27', sourceId: 'emailComponent', destinationId: 'email', description: 'Sends e-mail using', technology: 'SMTP', tags: ['Relationship'], properties: {} },
        { id: 'r28', sourceId: 'mainframeFacade', destinationId: 'mainframe', description: 'Makes API calls', technology: 'XML/HTTPS', tags: ['Relationship'], properties: {} },
      ],
      groups: [],
    },
    views: {
      systemLandscapeViews: [
        {
          type: 'systemLandscape',
          key: 'SystemLandscape',
          title: 'System Landscape',
          description: 'The system landscape for Big Bank plc.',
          elements: [
            { id: 'customer' },
            { id: 'internetBanking' },
            { id: 'mainframe' },
            { id: 'email' },
            { id: 'atm' },
            { id: 'supportStaff' },
            { id: 'backoffice' },
          ],
          relationships: [
            { id: 'r1' }, { id: 'r2' }, { id: 'r3' }, { id: 'r4' },
            { id: 'r5' }, { id: 'r6' }, { id: 'r7' }, { id: 'r8' }, { id: 'r9' },
          ],
          autoLayout: { direction: 'TB' },
        },
      ],
      systemContextViews: [
        {
          type: 'systemContext',
          key: 'SystemContext',
          title: 'System Context',
          description: 'The system context for Internet Banking.',
          softwareSystemId: 'internetBanking',
          elements: [
            { id: 'customer' },
            { id: 'internetBanking' },
            { id: 'mainframe' },
            { id: 'email' },
          ],
          relationships: [
            { id: 'r1' }, { id: 'r2' }, { id: 'r3' }, { id: 'r4' },
          ],
          autoLayout: { direction: 'TB' },
        },
      ],
      containerViews: [
        {
          type: 'container',
          key: 'Containers',
          title: 'Containers',
          description: 'The containers within Internet Banking.',
          softwareSystemId: 'internetBanking',
          elements: [
            { id: 'customer' },
            { id: 'singlePageApp' },
            { id: 'mobileApp' },
            { id: 'webApp' },
            { id: 'apiApp' },
            { id: 'database' },
            { id: 'mainframe' },
            { id: 'email' },
          ],
          relationships: [
            { id: 'r10' }, { id: 'r11' }, { id: 'r12' }, { id: 'r13' },
            { id: 'r14' }, { id: 'r15' }, { id: 'r16' }, { id: 'r17' }, { id: 'r18' },
          ],
          autoLayout: { direction: 'TB' },
        },
      ],
      componentViews: [
        {
          type: 'component',
          key: 'Components',
          title: 'Components',
          description: 'The components within the API Application.',
          containerId: 'apiApp',
          elements: [
            { id: 'singlePageApp' },
            { id: 'signinController' },
            { id: 'resetPassController' },
            { id: 'accountsSummary' },
            { id: 'securityComponent' },
            { id: 'emailComponent' },
            { id: 'mainframeFacade' },
            { id: 'database' },
            { id: 'email' },
            { id: 'mainframe' },
          ],
          relationships: [
            { id: 'r19' }, { id: 'r20' }, { id: 'r21' }, { id: 'r22' },
            { id: 'r23' }, { id: 'r24' }, { id: 'r25' }, { id: 'r26' },
            { id: 'r27' }, { id: 'r28' },
          ],
          autoLayout: { direction: 'TB' },
        },
      ],
      configuration: {
        styles: {
          elements: [
            { tag: 'Bank Staff', background: '#1e2832', color: '#94a3b8', stroke: '#475569' },
            { tag: 'Existing System', background: '#2a2018', color: '#d4a96a', stroke: '#a37032' },
            { tag: 'Database', background: '#1e1a40', color: '#c4b5fd', stroke: '#7c3aed', shape: 'Cylinder' },
          ],
          relationships: [],
        },
      },
    },
  }
}

/** Microservices architecture — API gateway + services + message broker */
export function createMicroservicesTemplate(): Workspace {
  return {
    name: 'Microservices Architecture',
    description: 'An API gateway with microservices, message broker, and backing data stores.',
    model: {
      people: [
        {
          id: 'customer',
          type: 'person',
          name: 'Customer',
          description: 'A user of the platform who interacts via web or mobile.',
          tags: ['Person', 'Customer'],
          properties: {},
          location: 'External',
        },
      ],
      softwareSystems: [
        {
          id: 'platform',
          type: 'softwareSystem',
          name: 'E-Commerce Platform',
          description: 'The microservices-based e-commerce platform.',
          tags: ['Software System'],
          properties: {},
          location: 'Internal',
          containers: [
            {
              id: 'apiGateway',
              type: 'container',
              name: 'API Gateway',
              description: 'Routes requests to the appropriate microservice and handles authentication.',
              technology: 'Node.js, Express',
              tags: ['Container'],
              properties: {},
              components: [],
            },
            {
              id: 'userService',
              type: 'container',
              name: 'User Service',
              description: 'Manages user accounts, authentication, and profiles.',
              technology: 'Java, Spring Boot',
              tags: ['Container'],
              properties: {},
              components: [],
            },
            {
              id: 'orderService',
              type: 'container',
              name: 'Order Service',
              description: 'Handles order creation, tracking, and fulfilment.',
              technology: 'Java, Spring Boot',
              tags: ['Container'],
              properties: {},
              components: [],
            },
            {
              id: 'productService',
              type: 'container',
              name: 'Product Service',
              description: 'Manages the product catalogue and inventory.',
              technology: 'Go',
              tags: ['Container'],
              properties: {},
              components: [],
            },
            {
              id: 'postgres',
              type: 'container',
              name: 'PostgreSQL',
              description: 'Primary relational data store for users, orders, and products.',
              technology: 'PostgreSQL 15',
              tags: ['Container', 'Database'],
              properties: {},
              components: [],
            },
            {
              id: 'redis',
              type: 'container',
              name: 'Redis',
              description: 'In-memory cache and session store.',
              technology: 'Redis 7',
              tags: ['Container', 'Database'],
              properties: {},
              components: [],
            },
            {
              id: 'rabbitMQ',
              type: 'container',
              name: 'RabbitMQ',
              description: 'Message broker for asynchronous communication between services.',
              technology: 'RabbitMQ',
              tags: ['Container', 'Queue'],
              properties: {},
              components: [],
            },
          ],
        },
      ],
      relationships: [
        { id: 'r1', sourceId: 'customer', destinationId: 'platform', description: 'Browses products, places orders', tags: ['Relationship'], properties: {} },
        { id: 'r2', sourceId: 'customer', destinationId: 'apiGateway', description: 'Makes API requests', technology: 'HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r3', sourceId: 'apiGateway', destinationId: 'userService', description: 'Routes auth requests', technology: 'gRPC', tags: ['Relationship'], properties: {} },
        { id: 'r4', sourceId: 'apiGateway', destinationId: 'orderService', description: 'Routes order requests', technology: 'gRPC', tags: ['Relationship'], properties: {} },
        { id: 'r5', sourceId: 'apiGateway', destinationId: 'productService', description: 'Routes product requests', technology: 'gRPC', tags: ['Relationship'], properties: {} },
        { id: 'r6', sourceId: 'userService', destinationId: 'postgres', description: 'Reads from and writes to', technology: 'SQL', tags: ['Relationship'], properties: {} },
        { id: 'r7', sourceId: 'orderService', destinationId: 'postgres', description: 'Reads from and writes to', technology: 'SQL', tags: ['Relationship'], properties: {} },
        { id: 'r8', sourceId: 'productService', destinationId: 'postgres', description: 'Reads from and writes to', technology: 'SQL', tags: ['Relationship'], properties: {} },
        { id: 'r9', sourceId: 'apiGateway', destinationId: 'redis', description: 'Caches sessions and tokens', technology: 'Redis Protocol', tags: ['Relationship'], properties: {} },
        { id: 'r10', sourceId: 'orderService', destinationId: 'rabbitMQ', description: 'Publishes order events', technology: 'AMQP', tags: ['Relationship'], properties: {} },
        { id: 'r11', sourceId: 'productService', destinationId: 'rabbitMQ', description: 'Consumes inventory updates', technology: 'AMQP', tags: ['Relationship'], properties: {} },
        { id: 'r12', sourceId: 'userService', destinationId: 'rabbitMQ', description: 'Publishes user events', technology: 'AMQP', tags: ['Relationship'], properties: {} },
      ],
      groups: [],
    },
    views: {
      systemLandscapeViews: [
        {
          type: 'systemLandscape',
          key: 'SystemLandscape',
          title: 'System Landscape',
          description: 'Overview of the microservices platform.',
          elements: [
            { id: 'customer' },
            { id: 'platform' },
          ],
          relationships: [
            { id: 'r1' },
          ],
          autoLayout: { direction: 'TB' },
        },
      ],
      systemContextViews: [],
      containerViews: [
        {
          type: 'container',
          key: 'Containers',
          title: 'Containers',
          description: 'The microservices, data stores, and message broker.',
          softwareSystemId: 'platform',
          elements: [
            { id: 'customer' },
            { id: 'apiGateway' },
            { id: 'userService' },
            { id: 'orderService' },
            { id: 'productService' },
            { id: 'postgres' },
            { id: 'redis' },
            { id: 'rabbitMQ' },
          ],
          relationships: [
            { id: 'r2' }, { id: 'r3' }, { id: 'r4' }, { id: 'r5' },
            { id: 'r6' }, { id: 'r7' }, { id: 'r8' }, { id: 'r9' },
            { id: 'r10' }, { id: 'r11' }, { id: 'r12' },
          ],
          autoLayout: { direction: 'TB' },
        },
      ],
      componentViews: [],
      configuration: {
        styles: {
          elements: [
            { tag: 'Database', background: '#1e1a40', color: '#c4b5fd', stroke: '#7c3aed', shape: 'Cylinder' },
            { tag: 'Queue', background: '#2d1f0d', color: '#fdba74', stroke: '#f97316' },
          ],
          relationships: [],
        },
      },
    },
  }
}

/** Monolithic architecture — frontend, backend, and database */
export function createMonolithTemplate(): Workspace {
  return {
    name: 'Monolithic Application',
    description: 'A traditional monolithic web application with frontend, backend, and database.',
    model: {
      people: [
        {
          id: 'admin',
          type: 'person',
          name: 'Administrator',
          description: 'An internal administrator who manages content and users.',
          tags: ['Person', 'Staff'],
          properties: {},
          location: 'Internal',
        },
        {
          id: 'endUser',
          type: 'person',
          name: 'End User',
          description: 'A public user who interacts with the application.',
          tags: ['Person', 'Customer'],
          properties: {},
          location: 'External',
        },
      ],
      softwareSystems: [
        {
          id: 'monolith',
          type: 'softwareSystem',
          name: 'Monolithic Application',
          description: 'The primary web application serving all business functionality.',
          tags: ['Software System'],
          properties: {},
          location: 'Internal',
          containers: [
            {
              id: 'webFrontend',
              type: 'container',
              name: 'Web Frontend',
              description: 'Delivers the user interface to browsers.',
              technology: 'React, TypeScript',
              tags: ['Container'],
              properties: {},
              components: [],
            },
            {
              id: 'backendApp',
              type: 'container',
              name: 'Backend Application',
              description: 'Handles business logic, API endpoints, and server-side rendering.',
              technology: 'Python, Django',
              tags: ['Container'],
              properties: {},
              components: [],
            },
            {
              id: 'database',
              type: 'container',
              name: 'Database',
              description: 'Stores all application data including users, content, and configuration.',
              technology: 'MySQL 8',
              tags: ['Container', 'Database'],
              properties: {},
              components: [],
            },
          ],
        },
        {
          id: 'emailService',
          type: 'softwareSystem',
          name: 'E-mail Service',
          description: 'Third-party transactional email provider.',
          tags: ['Software System', 'External System'],
          properties: {},
          location: 'External',
          containers: [],
        },
      ],
      relationships: [
        { id: 'r1', sourceId: 'endUser', destinationId: 'monolith', description: 'Uses the application', tags: ['Relationship'], properties: {} },
        { id: 'r2', sourceId: 'admin', destinationId: 'monolith', description: 'Manages content and users', tags: ['Relationship'], properties: {} },
        { id: 'r3', sourceId: 'monolith', destinationId: 'emailService', description: 'Sends transactional emails via', tags: ['Relationship'], properties: {} },
        { id: 'r4', sourceId: 'emailService', destinationId: 'endUser', description: 'Sends emails to', tags: ['Relationship'], properties: {} },
        { id: 'r5', sourceId: 'endUser', destinationId: 'webFrontend', description: 'Visits and interacts', technology: 'HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r6', sourceId: 'admin', destinationId: 'webFrontend', description: 'Manages via admin panel', technology: 'HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r7', sourceId: 'webFrontend', destinationId: 'backendApp', description: 'Makes API calls', technology: 'JSON/HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r8', sourceId: 'backendApp', destinationId: 'database', description: 'Reads from and writes to', technology: 'SQL', tags: ['Relationship'], properties: {} },
        { id: 'r9', sourceId: 'backendApp', destinationId: 'emailService', description: 'Sends emails via', technology: 'SMTP', tags: ['Relationship'], properties: {} },
      ],
      groups: [],
    },
    views: {
      systemLandscapeViews: [
        {
          type: 'systemLandscape',
          key: 'SystemLandscape',
          title: 'System Landscape',
          description: 'Overview of the monolithic application and its users.',
          elements: [
            { id: 'admin' },
            { id: 'endUser' },
            { id: 'monolith' },
            { id: 'emailService' },
          ],
          relationships: [
            { id: 'r1' }, { id: 'r2' }, { id: 'r3' }, { id: 'r4' },
          ],
          autoLayout: { direction: 'TB' },
        },
      ],
      systemContextViews: [],
      containerViews: [
        {
          type: 'container',
          key: 'Containers',
          title: 'Containers',
          description: 'The frontend, backend, and database within the monolith.',
          softwareSystemId: 'monolith',
          elements: [
            { id: 'admin' },
            { id: 'endUser' },
            { id: 'webFrontend' },
            { id: 'backendApp' },
            { id: 'database' },
            { id: 'emailService' },
          ],
          relationships: [
            { id: 'r5' }, { id: 'r6' }, { id: 'r7' }, { id: 'r8' }, { id: 'r9' },
          ],
          autoLayout: { direction: 'TB' },
        },
      ],
      componentViews: [],
      configuration: {
        styles: {
          elements: [
            { tag: 'Staff', background: '#1e2832', color: '#94a3b8', stroke: '#475569' },
            { tag: 'External System', background: '#201c28', color: '#c084fc', stroke: '#9333ea' },
            { tag: 'Database', background: '#1e1a40', color: '#c4b5fd', stroke: '#7c3aed', shape: 'Cylinder' },
          ],
          relationships: [],
        },
      },
    },
  }
}

/** Event-driven architecture — producers, Kafka, consumers, data lake */
export function createEventDrivenTemplate(): Workspace {
  return {
    name: 'Event-Driven Architecture',
    description: 'An event-driven system with producer services, Kafka, consumer services, and a data lake.',
    model: {
      people: [
        {
          id: 'analyst',
          type: 'person',
          name: 'Data Analyst',
          description: 'Queries the data lake for business intelligence and reporting.',
          tags: ['Person', 'Staff'],
          properties: {},
          location: 'Internal',
        },
      ],
      softwareSystems: [
        {
          id: 'eventPlatform',
          type: 'softwareSystem',
          name: 'Event-Driven Platform',
          description: 'The event-driven data processing platform.',
          tags: ['Software System'],
          properties: {},
          location: 'Internal',
          containers: [
            {
              id: 'ingestService',
              type: 'container',
              name: 'Ingest Service',
              description: 'Receives data from external sources and publishes events.',
              technology: 'Python, FastAPI',
              tags: ['Container', 'Producer'],
              properties: {},
              components: [],
            },
            {
              id: 'clickstreamService',
              type: 'container',
              name: 'Clickstream Collector',
              description: 'Captures user interaction events from web and mobile clients.',
              technology: 'Go',
              tags: ['Container', 'Producer'],
              properties: {},
              components: [],
            },
            {
              id: 'kafka',
              type: 'container',
              name: 'Apache Kafka',
              description: 'Distributed event streaming platform and central message backbone.',
              technology: 'Apache Kafka',
              tags: ['Container', 'Queue'],
              properties: {},
              components: [],
            },
            {
              id: 'enrichmentService',
              type: 'container',
              name: 'Enrichment Service',
              description: 'Consumes raw events, enriches with metadata, and re-publishes.',
              technology: 'Java, Kafka Streams',
              tags: ['Container', 'Consumer'],
              properties: {},
              components: [],
            },
            {
              id: 'analyticsService',
              type: 'container',
              name: 'Analytics Service',
              description: 'Processes enriched events and generates aggregated metrics.',
              technology: 'Scala, Apache Flink',
              tags: ['Container', 'Consumer'],
              properties: {},
              components: [],
            },
            {
              id: 'notificationService',
              type: 'container',
              name: 'Notification Service',
              description: 'Listens for specific events and sends alerts via email and push notifications.',
              technology: 'Node.js',
              tags: ['Container', 'Consumer'],
              properties: {},
              components: [],
            },
            {
              id: 'dataLake',
              type: 'container',
              name: 'Data Lake',
              description: 'Long-term storage for raw and processed event data.',
              technology: 'AWS S3, Apache Parquet',
              tags: ['Container', 'Database'],
              properties: {},
              components: [],
            },
          ],
        },
        {
          id: 'externalSource',
          type: 'softwareSystem',
          name: 'External Data Source',
          description: 'Third-party systems that push data into the platform.',
          tags: ['Software System', 'External System'],
          properties: {},
          location: 'External',
          containers: [],
        },
      ],
      relationships: [
        { id: 'r1', sourceId: 'externalSource', destinationId: 'eventPlatform', description: 'Sends data to', tags: ['Relationship'], properties: {} },
        { id: 'r2', sourceId: 'analyst', destinationId: 'eventPlatform', description: 'Queries for reports', tags: ['Relationship'], properties: {} },
        { id: 'r3', sourceId: 'externalSource', destinationId: 'ingestService', description: 'Pushes data via webhooks', technology: 'HTTPS', tags: ['Relationship'], properties: {} },
        { id: 'r4', sourceId: 'ingestService', destinationId: 'kafka', description: 'Publishes raw events', technology: 'Kafka Protocol', tags: ['Relationship'], properties: {} },
        { id: 'r5', sourceId: 'clickstreamService', destinationId: 'kafka', description: 'Publishes clickstream events', technology: 'Kafka Protocol', tags: ['Relationship'], properties: {} },
        { id: 'r6', sourceId: 'kafka', destinationId: 'enrichmentService', description: 'Delivers raw events', technology: 'Kafka Protocol', tags: ['Relationship'], properties: {} },
        { id: 'r7', sourceId: 'enrichmentService', destinationId: 'kafka', description: 'Publishes enriched events', technology: 'Kafka Protocol', tags: ['Relationship'], properties: {} },
        { id: 'r8', sourceId: 'kafka', destinationId: 'analyticsService', description: 'Delivers enriched events', technology: 'Kafka Protocol', tags: ['Relationship'], properties: {} },
        { id: 'r9', sourceId: 'kafka', destinationId: 'notificationService', description: 'Delivers alert-worthy events', technology: 'Kafka Protocol', tags: ['Relationship'], properties: {} },
        { id: 'r10', sourceId: 'analyticsService', destinationId: 'dataLake', description: 'Writes aggregated data', technology: 'S3 API', tags: ['Relationship'], properties: {} },
        { id: 'r11', sourceId: 'enrichmentService', destinationId: 'dataLake', description: 'Archives enriched events', technology: 'S3 API', tags: ['Relationship'], properties: {} },
        { id: 'r12', sourceId: 'analyst', destinationId: 'dataLake', description: 'Queries for analytics', technology: 'SQL / Athena', tags: ['Relationship'], properties: {} },
      ],
      groups: [],
    },
    views: {
      systemLandscapeViews: [
        {
          type: 'systemLandscape',
          key: 'SystemLandscape',
          title: 'System Landscape',
          description: 'Overview of the event-driven platform.',
          elements: [
            { id: 'analyst' },
            { id: 'eventPlatform' },
            { id: 'externalSource' },
          ],
          relationships: [
            { id: 'r1' }, { id: 'r2' },
          ],
          autoLayout: { direction: 'TB' },
        },
      ],
      systemContextViews: [],
      containerViews: [
        {
          type: 'container',
          key: 'Containers',
          title: 'Containers',
          description: 'Producers, Kafka, consumers, and data lake.',
          softwareSystemId: 'eventPlatform',
          elements: [
            { id: 'analyst' },
            { id: 'externalSource' },
            { id: 'ingestService' },
            { id: 'clickstreamService' },
            { id: 'kafka' },
            { id: 'enrichmentService' },
            { id: 'analyticsService' },
            { id: 'notificationService' },
            { id: 'dataLake' },
          ],
          relationships: [
            { id: 'r3' }, { id: 'r4' }, { id: 'r5' }, { id: 'r6' },
            { id: 'r7' }, { id: 'r8' }, { id: 'r9' }, { id: 'r10' },
            { id: 'r11' }, { id: 'r12' },
          ],
          autoLayout: { direction: 'TB' },
        },
      ],
      componentViews: [],
      configuration: {
        styles: {
          elements: [
            { tag: 'Staff', background: '#1e2832', color: '#94a3b8', stroke: '#475569' },
            { tag: 'External System', background: '#201c28', color: '#c084fc', stroke: '#9333ea' },
            { tag: 'Producer', background: '#0e2a1a', color: '#6ee7b7', stroke: '#059669' },
            { tag: 'Consumer', background: '#2d0f0f', color: '#fca5a5', stroke: '#ef4444' },
            { tag: 'Queue', background: '#2d1f0d', color: '#fdba74', stroke: '#f97316' },
            { tag: 'Database', background: '#1e1a40', color: '#c4b5fd', stroke: '#7c3aed', shape: 'Cylinder' },
          ],
          relationships: [],
        },
      },
    },
  }
}

/** Empty workspace for starting from scratch */
export function createBlankWorkspace(): Workspace {
  return {
    name: 'Untitled Workspace',
    description: '',
    model: {
      people: [],
      softwareSystems: [],
      relationships: [],
      groups: [],
    },
    views: {
      systemLandscapeViews: [
        {
          type: 'systemLandscape',
          key: 'default',
          title: 'System Landscape',
          elements: [],
          relationships: [],
          autoLayout: { direction: 'TB' },
        },
      ],
      systemContextViews: [],
      containerViews: [],
      componentViews: [],
      configuration: {
        styles: {
          elements: [],
          relationships: [],
        },
      },
    },
  }
}
