#!/usr/bin/env bash
# Task: Conformance harness: hostile fixture, emitter, strict tokenizer test, real Structurizr CLI runner (t4)
# Run: run-2026-08-02T14-20-47-900Z-hrxwc
set -euo pipefail

test -f src/lib/dsl/__fixtures__/hostile-strings.ts && test -f src/lib/dsl/conformance-emit.test.ts && test -f src/lib/dsl/strict-structurizr-tokenizer.test.ts && test -f scripts/structurizr-conformance.mjs
node -e 'const s=require("fs").readFileSync("src/lib/dsl/__fixtures__/hostile-strings.ts","utf8");const need=[["exported factory function",/export\s+(function|const)/],["Workspace type",/Workspace/],["HOST-01 marker",/HOST-01/],["element name Shared Folder X:",/Shared Folder X:/],["windows path C:\\Users\\svc",/C:\\+Users\\+svc/],["embedded newline escape",/\\n/],["embedded tab escape",/\\t/],["external location",/External/],["owner",/owner/],["status",/status/],["lineStyle",/lineStyle/],["interactionStyle",/interactionStyle/],["relationship properties",/properties/],["relationship url",/url/],["view with autoLayout",/autoLayout/]];const miss=need.filter(function(n){return !n[1].test(s)}).map(function(n){return n[0]});if(miss.length){console.error("hostile fixture is missing:",miss.join(", "));process.exit(1)}console.log("hostile fixture ok")'
node -e 'const fs=require("fs"),cp=require("child_process");const cur=JSON.parse(fs.readFileSync("package.json","utf8"));const base=JSON.parse(cp.execSync("git show HEAD:package.json",{encoding:"utf8"}));const names=function(o){return Object.keys(Object.assign({},o.dependencies,o.devDependencies,o.optionalDependencies,o.peerDependencies))};const added=names(cur).filter(function(n){return names(base).indexOf(n)===-1});if(added.length){console.error("new dependency added (none allowed):",added.join(", "));process.exit(1)}const s=cur.scripts||{};if(s["dsl:conformance:emit"]!=="vitest run src/lib/dsl/conformance-emit.test.ts"){console.error("wrong dsl:conformance:emit script:",s["dsl:conformance:emit"]);process.exit(1)}if(s["dsl:conformance"]!=="npm run dsl:conformance:emit && node scripts/structurizr-conformance.mjs"){console.error("wrong dsl:conformance script:",s["dsl:conformance"]);process.exit(1)}console.log("package.json scripts ok, no new dependencies")'
node -e 'const s=require("fs").readFileSync("scripts/structurizr-conformance.mjs","utf8");const builtin=require("module").builtinModules;const err=[];if(!s.includes("v2025.11.09"))err.push("pinned CLI version v2025.11.09 not referenced");if(!s.includes("https://github.com/structurizr/cli/releases/download/v2025.11.09/structurizr-cli.zip"))err.push("pinned archive URL not referenced");if(!s.includes("STRUCTURIZR_CLI_HOME"))err.push("STRUCTURIZR_CLI_HOME override not supported");if(!s.includes(".structurizr-cli"))err.push("cache directory .structurizr-cli not used");if(!s.includes(".conformance-dsl"))err.push("corpus directory .conformance-dsl not used");if(!s.includes("--self-test"))err.push("--self-test mode missing");["unzip","jar","zipfile"].forEach(function(t){if(!s.includes(t))err.push("extraction fallback missing: "+t)});const specs=[].concat(Array.from(s.matchAll(/import\s[^;]*?from\s*["\x27]([^"\x27]+)["\x27]/g)),Array.from(s.matchAll(/import\(\s*["\x27]([^"\x27]+)["\x27]/g)),Array.from(s.matchAll(/require\(\s*["\x27]([^"\x27]+)["\x27]/g))).map(function(m){return m[1]});const ext=specs.filter(function(x){return !x.startsWith("node:")&&!x.startsWith(".")&&!x.startsWith("/")&&builtin.indexOf(x)===-1});if(ext.length)err.push("non-builtin imports (no new dependencies allowed): "+ext.join(", "));if(err.length){console.error(err.join("\n"));process.exit(1)}console.log("conformance script ok:",specs.length,"imports, all node builtins")'
git check-ignore -q .conformance-dsl/x.dsl && git check-ignore -q .structurizr-cli/v2025.11.09/structurizr.sh && test -z "$(git ls-files -- .conformance-dsl .structurizr-cli)" && echo "generated dirs are git-ignored and untracked"
npx vitest run src/lib/dsl/conformance-emit.test.ts src/lib/dsl/strict-structurizr-tokenizer.test.ts
f=src/lib/dsl/conformance-emit.test.ts; if grep -nE '(it|test|describe)\.(skip|todo|only)|\bxit\(|\bxdescribe\(' "$f"; then echo "conformance-emit test skips or narrows cases"; exit 1; fi; if grep -nE '\.(location|owner|status|lineStyle|interactionStyle)[[:space:]]*=[^=]' "$f"; then echo "conformance-emit test scrubs in-scope fields instead of fixing the serializer"; exit 1; fi; if grep -nE 'replace\([^)]*(location|owner|status|lineStyle|interactionStyle)' "$f"; then echo "conformance-emit test post-processes emitted DSL to hide in-scope defects"; exit 1; fi; echo "no exclusions or field scrubbing in conformance-emit test"
f=src/lib/dsl/strict-structurizr-tokenizer.test.ts; grep -qE '(function|const)[[:space:]]+[A-Za-z_]*[Tt]oken' "$f" || { echo "no locally defined tokenizer in $f"; exit 1; }; grep -qi 'unterminated' "$f" || { echo "tokenizer test does not assert on unterminated strings"; exit 1; }; grep -qF 'hostile-strings' "$f" || { echo "tokenizer test does not tokenise the hostile fixture output"; exit 1; }; grep -qiE 'serializ' "$f" || { echo "tokenizer test does not tokenise serializer output"; exit 1; }; if grep -nE 'from [^;]*[Ll]exer' "$f"; then echo "strict tokenizer must be self-contained, not an import of the c4hero lexer"; exit 1; fi; echo "strict tokenizer test ok"
node -e 'const fs=require("fs");const dir=".conformance-dsl";const files=fs.existsSync(dir)?fs.readdirSync(dir).filter(function(f){return f.endsWith(".dsl")}).sort():[];if(files.length<4){console.error("expected at least 4 emitted .dsl files in "+dir+", got "+files.length);process.exit(1)}let all="";const bad=[];files.forEach(function(f){const t=fs.readFileSync(dir+"/"+f,"utf8");all+=t;t.split(/\r?\n/).forEach(function(l,i){const at=f+":"+(i+1)+" ";if(/^\s*(location|owner|status|lineStyle|interactionStyle)\s/.test(l))bad.push(at+"forbidden statement: "+l.trim());if(/\\\\/.test(l))bad.push(at+"double-backslash escape: "+l.trim());if(/\\n|\\t/.test(l))bad.push(at+"escape sequence: "+l.trim());const m=l.match(/^\s*autoLayout\b(.*)$/);if(m&&/[A-Z]/.test(m[1]))bad.push(at+"non-lowercase autoLayout direction: "+l.trim())})});if(!/HOST-01/.test(all))bad.push("hostile fixture marker HOST-01 absent from the emitted corpus");if(!/Shared Folder X:/.test(all))bad.push("hostile element name absent from the emitted corpus");if(bad.length){console.error(bad.join("\n"));process.exit(1)}console.log("offline invariants hold across "+files.length+" emitted files")'
set -e; mkdir -p .fluxtmp/checks; if ! node scripts/structurizr-conformance.mjs --self-test > .fluxtmp/checks/selftest.log 2>&1; then echo "--self-test exited non-zero"; cat .fluxtmp/checks/selftest.log; exit 1; fi; cat .fluxtmp/checks/selftest.log; grep -qi 'reject' .fluxtmp/checks/selftest.log || { echo "self-test output does not show the CLI rejecting the invalid snippet"; exit 1; }
node -e 'const p=(process.env.FLUX_CHANGED_PATHS||"").split("\n").map(function(s){return s.trim()}).filter(Boolean);const bad=p.filter(function(f){const n=f.replace(/^\.\//,"");return n.startsWith(".conformance-dsl/")||n.startsWith(".structurizr-cli/")||/\.(zip|jar|class)$/.test(n)||(/\.dsl$/.test(n)&&!n.startsWith("src/lib/dsl/__fixtures__/"))});if(bad.length){console.error("generated conformance output or CLI binaries must not be part of the change:",bad.join(", "));process.exit(1)}console.log("scope ok:",p.length,"changed paths")'
